export const data_champions = [
  {
    name: "Target Dummy",
    championId: "TFT_TrainingDummy",
    cost: 2,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Aatrox",
    championId: "TFT5_Aatrox",
    cost: 1,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 2,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 1,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Akshan",
    championId: "TFT5_Akshan",
    cost: 5,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 2,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 1,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Aphelios",
    championId: "TFT5_Aphelios",
    cost: 4,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 1,
    Ranger: 2,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Ashe",
    championId: "TFT5_Ashe",
    cost: 3,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 1,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 2,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Brand",
    championId: "TFT5_Brand",
    cost: 2,
    Abomination: 1,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 2,
    Victorious: 0
  },
  {
    name: "Diana",
    championId: "TFT5_Diana",
    cost: 4,
    Abomination: 0,
    Assassin: 2,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 1,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Draven",
    championId: "TFT5_Draven",
    cost: 4,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 1,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 2,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Fiddlesticks",
    championId: "TFT5_Fiddlesticks",
    cost: 4,
    Abomination: 1,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 2,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 1,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Galio",
    championId: "TFT5_Galio",
    cost: 4,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 1,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 2,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 1,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Garen",
    championId: "TFT5_Garen",
    cost: 5,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 1,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 2,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 1
  },
  {
    name: "Gragas",
    championId: "TFT5_Gragas",
    cost: 1,
    Abomination: 0,
    Assassin: 0,
    Brawler: 2,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 1,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Gwen",
    championId: "TFT5_Gwen",
    cost: 5,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 1,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 2,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Hecarim",
    championId: "TFT5_Hecarim",
    cost: 2,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 2,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 1,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Heimerdinger",
    championId: "TFT5_Heimerdinger",
    cost: 5,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 2,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 1,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 2,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Ivern",
    championId: "TFT5_Ivern",
    cost: 4,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 2,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 2,
    Revenant: 1,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Irelia",
    championId: "TFT5_Irelia",
    cost: 2,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 2,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 1,
    Skirmisher: 2,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Jax",
    championId: "TFT5_Jax",
    cost: 4,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 1,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 2,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Kalista",
    championId: "TFT5_Kalista",
    cost: 1,
    Abomination: 1,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 2,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Karma",
    championId: "TFT5_Karma",
    cost: 4,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 1,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 2,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Kayle",
    championId: "TFT5_Kayle",
    cost: 5,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 2,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 1,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Kennen",
    championId: "TFT5_Kennen",
    cost: 2,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 1,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 2,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Kha'Zix",
    championId: "TFT5_Khazix",
    cost: 1,
    Abomination: 0,
    Assassin: 2,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 1,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Kled",
    championId: "TFT5_Kled",
    cost: 1,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 2,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 1,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Lee Sin",
    championId: "TFT5_LeeSin",
    cost: 3,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 1,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 2,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Leona",
    championId: "TFT5_Leona",
    cost: 1,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 2,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 1,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Lucian",
    championId: "TFT5_Lucian",
    cost: 4,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 2,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 1,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Lulu",
    championId: "TFT5_Lulu",
    cost: 3,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 1,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 2,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Lux",
    championId: "TFT5_Lux",
    cost: 3,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 2,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 1,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Miss Fortune",
    championId: "TFT5_MissFortune",
    cost: 3,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 2,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 1,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Nautilus",
    championId: "TFT5_Nautilus",
    cost: 2,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 1,
    Knight: 2,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Nidalee",
    championId: "TFT5_Nidalee",
    cost: 3,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 1,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 2,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Nocturne",
    championId: "TFT5_Nocturne",
    cost: 3,
    Abomination: 0,
    Assassin: 2,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 1,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Nunu",
    championId: "TFT5_Nunu",
    cost: 3,
    Abomination: 1,
    Assassin: 0,
    Brawler: 2,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Olaf",
    championId: "TFT5_Olaf",
    cost: 1,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 1,
    Skirmisher: 2,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Poppy",
    championId: "TFT5_Poppy",
    cost: 1,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 1,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 2,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Pyke",
    championId: "TFT5_Pyke",
    cost: 2,
    Abomination: 0,
    Assassin: 2,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 1,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Rakan",
    championId: "TFT5_Rakan",
    cost: 3,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 2,
    Revenant: 0,
    Sentinel: 1,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Rell",
    championId: "TFT5_Rell",
    cost: 4,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 2,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 1,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 1,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Riven",
    championId: "TFT5_Riven",
    cost: 3,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 1,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 2,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Sejuani",
    championId: "TFT5_Sejuani",
    cost: 2,
    Abomination: 0,
    Assassin: 0,
    Brawler: 2,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 2,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 1,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Senna",
    championId: "TFT5_Senna",
    cost: 1,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 2,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 1,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Sett",
    championId: "TFT5_Sett",
    cost: 2,
    Abomination: 0,
    Assassin: 0,
    Brawler: 2,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 1,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Soraka",
    championId: "TFT5_Soraka",
    cost: 2,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 1,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 2,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Syndra",
    championId: "TFT5_Syndra",
    cost: 2,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 2,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 1,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Teemo",
    championId: "TFT5_Teemo",
    cost: 5,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 1,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 1,
    Inanimate: 0,
    Invoker: 2,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Thresh",
    championId: "TFT5_Thresh",
    cost: 2,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 1,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 2,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Tristana",
    championId: "TFT5_Tristana",
    cost: 2,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 2,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 1,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Udyr",
    championId: "TFT5_Udyr",
    cost: 1,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 1,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 2,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Varus",
    championId: "TFT5_Varus",
    cost: 2,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 2,
    Redeemed: 1,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Vayne",
    championId: "TFT5_Vayne",
    cost: 1,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 1,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 2,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Vel'Koz",
    championId: "TFT5_Velkoz",
    cost: 4,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 1,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 2,
    Victorious: 0
  },
  {
    name: "Viego",
    championId: "TFT5_Viego",
    cost: 5,
    Abomination: 0,
    Assassin: 2,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 1,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 2,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Vladimir",
    championId: "TFT5_Vladimir",
    cost: 1,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 1,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 2,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Volibear",
    championId: "TFT5_Volibear",
    cost: 5,
    Abomination: 0,
    Assassin: 0,
    Brawler: 2,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 1,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Yasuo",
    championId: "TFT5_Yasuo",
    cost: 3,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 2,
    Mystic: 0,
    Nightbringer: 1,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 0,
    Victorious: 0
  },
  {
    name: "Ziggs",
    championId: "TFT5_Ziggs",
    cost: 1,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 0,
    Forgotten: 0,
    Hellion: 1,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 2,
    Victorious: 0
  },
  {
    name: "Zyra",
    championId: "TFT5_Zyra",
    cost: 3,
    Abomination: 0,
    Assassin: 0,
    Brawler: 0,
    Cannoneer: 0,
    Caretaker: 0,
    Cavalier: 0,
    Cruel: 0,
    Dawnbringer: 0,
    Draconic: 1,
    Forgotten: 0,
    Hellion: 0,
    Inanimate: 0,
    Invoker: 0,
    Ironclad: 0,
    Knight: 0,
    Legionnaire: 0,
    Mystic: 0,
    Nightbringer: 0,
    Ranger: 0,
    Redeemed: 0,
    Renewer: 0,
    Revenant: 0,
    Sentinel: 0,
    Skirmisher: 0,
    Spellweaver: 2,
    Victorious: 0
  }
];
export const abilities_data = [
  {
    name: "Aatrox",
    title: "Deathbringer Strike",
    description:
      "Aatrox strikes his target, dealing a percentage of his Attack Damage, and heals himself."
  },
  {
    name: "Akshan",
    title: "Heroic Swing",
    description:
      "Passive: Akshan's attacks reduce the target's Armor by 50% for 5 seconds. Active: Akshan launches his grappling hook and swings untargetably toward the farthest enemy, gaining Attack Speed for 4 seconds. Akshan will continue to attack the nearest enemy at double his Attack Speed while swinging."
  },
  {
    name: "Aphelios",
    title: "Dark Vigil",
    description:
      "Aphelios launches multiple attacks simultaneously, one at his target and the rest at the enemies nearest to them, dealing a percentage of his Attack Damage plus bonus physical damage to each."
  },
  {
    name: "Ashe",
    title: "Enchanted Arrow",
    description:
      "Ashe fires an arrow at the farthest enemy, dealing magic damage to the first enemy hit and stunning them. If the arrow travels at least 5 hexes, the stun duration is doubled. Enemies within 1 hex receive 50% of these effects."
  },
  {
    name: "Brand",
    title: "Sear",
    description:
      "Brand launches a ball of fire at nearest non-seared enemy, searing them for magic damage over 12 seconds. Seared enemies have reduced Magic Resist."
  },
  {
    name: "Diana",
    title: "Moonfall",
    description:
      "Diana calls forth moonlight, drawing in all nearby enemies, dealing magic damage and stunning them for a few seconds."
  },
  {
    name: "Draven",
    title: "Spinning Axes",
    description:
      "Passive: Draven passively ignores 50% of his target’s Armor. Active: Draven starts spinning an axe, empowering his next attack to deal a percentage of his Attack Damage plus bonus physical damage. It will return to his location after striking the target and if Draven catches it, it will refresh the buff. Draven can spin up to two axes at a time."
  },
  {
    name: "Fiddlesticks",
    title: "Crowstorm",
    description:
      "After a brief channel, Fiddlesticks teleports behind his target and summons a murder of crows for a few seconds, dealing magic damage per second to all enemies within. Enemies that die within the flock extend its duration by 1 second and heal Fiddlesticks for a percentage of their maximum Health."
  },
  {
    name: "Galio",
    title: "Shield of Durand",
    description:
      "Galio charges the area around him for 2.5 seconds, taunting all enemies within while gaining Damage Reduction. Upon releasing the charge, Galio deals magic damage to all enemies within 3 hexes and heals for 60% of the damage blocked."
  },
  {
    name: "Garen",
    title: "God-Lion's Justice",
    description:
      "Garen calls down a sword that strikes a large area around his target, dealing a percentage of each target's max Health in magic damage and reducing their Magic Resist by 50% for 8 seconds. Garen gains a shield equal to a percentage of his maximum Health for 5 seconds."
  },
  {
    name: "Gragas",
    title: "Drunken Rage",
    description:
      "Gragas drinks from his cask, granting him damage reduction for 4 seconds, and causing his next Basic Attack to deal bonus magic damage."
  },
  {
    name: "Gwen",
    title: "Skip 'N Slash",
    description:
      "Gwen dashes around her target and performs 3 rapid snips in a cone in front of her, each dealing magic damage plus a percentage of the target’s maximum Health as magic damage. Snips steal Armor and Magic resist from their target. Every other cast, Gwen will perform double the amount of snips."
  },
  {
    name: "Hecarim",
    title: "Spirit of Dread",
    description:
      "Hecarim creates an aura around himself for 3 seconds. Each enemy within takes magic damage, and Hecarim heals himself for over the duration."
  },
  {
    name: "Heimerdinger",
    title: "Upgrade!!!",
    description:
      "Heimerdinger empowers his Baby Dragon, causing its next attack to be overcharged, launching three fireballs across the battlefield, dealing magic damage while burning enemies for 3% of the their maximum Health as true damage over 6 seconds, and reducing healing by 50% for the duration.If Heimerdinger does not have a turret, this spell will create one instead."
  },
  {
    name: "Irelia",
    title: "Defiant Dance",
    description:
      "Irelia surrounds herself with blades for 4 seconds, gaining damage reduction, increased by 10% each time she attacks, up to 90%. When the effect ends she strikes her target, dealing magic damage."
  },
  {
    name: "Ivern",
    title: "Daisy!",
    description:
      "Ivern summons his Sentinel friend Daisy to fight with him, gifting her Ability Power. Daisy immediately casts Shockwave upon arrival. If Daisy is already summoned, Ivern increases her Ability Power and commands her to cast Shockwave again."
  },
  {
    name: "Jax",
    title: "Empowered Strike",
    description:
      "Jax slams his target for a percentage of his Attack Damage and gains stacking Attack Speed for the remainder of combat. Jax leaps to the nearest enemy if no target is in his Attack Range."
  },
  {
    name: "Kalista",
    title: "Pierce",
    description:
      "Kalista hurls a spear towards the farthest enemy, dealing a percentage of her Attack Damage plus bonus physical damage to the first enemy it hits. If this kills the target, the spear continues and will deal the overkill damage to the next target it hits."
  },
  {
    name: "Karma",
    title: "Soulflare",
    description:
      "Karma fires a burst of energy towards a random enemy's location that detonates upon impact, dealing magic damage to adjacent enemies, and reducing Karma's maximum mana (down to a minimum of 10). Karma empowers every third cast, causing it to launch three bursts of energy toward different targets instead of one."
  },
  {
    name: "Kayle",
    title: "Divine Ascent",
    description:
      "Passive: Kayle ascends every few seconds, gaining additional bonuses. 1st: Attacks deal a percentage of Kayle's AD as bonus true damage. 2nd: Attacks explode around the target dealing her AD and bonus true damage to nearby enemies. 3rd: Every 12th attack grants Kayle damage immunity for 1 second. 4th: Hits cause swords to rain down, dealing magic damage."
  },
  {
    name: "Kennen",
    title: "Flame Rush",
    description:
      "Kennen engulfs himself in flame, dashing behind his target, then to the farthest enemy. Enemies he passes through are zapped dealing magic damage and stunning them for seconds."
  },
  {
    name: "Kha'Zix",
    title: "Taste Their Fear",
    description:
      "Kha'Zix slashes the nearest enemy, dealing magic damage. If the enemy has no adjacent allies, this damage is increased to."
  },
  {
    name: "Kled",
    title: "Violent Tendencies",
    description:
      "Passive: Kled enters combat on Skaarl, granting him a shield for 80% of his maximum health. Kled's every 4th attack deals 150% of his attack damage. When the shield is broken he dismounts, briefly becoming untargetable, and granting him Attack Speed."
  },
  {
    name: "Lee Sin",
    title: "Cripple",
    description:
      "Lee Sin slams the ground, dealing magic damage to nearby enemies and slowing their attack speed by 50% for 4 seconds."
  },
  {
    name: "Leona",
    title: "Solar Barrier",
    description:
      "Leona raises her shield, reducing all incoming damage by for 4 seconds."
  },
  {
    name: "Lucian",
    title: "The Culling",
    description:
      "Lucian fires 16 shots in a direction over 4 seconds, each hitting for 50% of his Attack Damage and dealing magic damage. Lucian fires extra shots based on his Attack Speed. Lucian will dash during The Culling to keep hitting enemies."
  },
  {
    name: "Lulu",
    title: "Whimsey",
    description:
      "Lulu casts an enchantment on the units nearest to her. If this enchants an ally, they gain bonus Attack Speed for 5 seconds. If this enchants an enemy, they are transformed into a docile feline for seconds, stunning them and causing them to take 20% increased damage."
  },
  {
    name: "Lux",
    title: "Prismatic Barrier",
    description:
      "Lux launches her wand toward her farthest ally, which returns to her shortly after reaching them. Lux and each ally touched by the wand are shielded for 3 seconds. Additionally, Lux empowers her next basic attack to deal an additional magic damage."
  },
  {
    name: "Miss Fortune",
    title: "Make it Rain",
    description:
      "Miss Fortune rains three waves of bullets down around her target, dealing magic damage to enemies in the area and reducing their incoming healing by 50% for 8 seconds."
  },
  {
    name: "Nautilus",
    title: "Anchor Slam",
    description:
      "Nautilus erupts the ground beneath his target, knocking them up and stunning them for a few seconds and dealing magic damage. Enemies adjacent to the target receive half of this effect."
  },
  {
    name: "Nidalee",
    title: "Aspect of the Cougar",
    description:
      "Nidalee transforms into a cougar and leaps behind the lowest Health enemy. While in cougar form, Nidalee gains 40% Dodge Chance, Attack Speed, and her attacks become melee attacks that deal bonus magic damage every 4th attack."
  },
  {
    name: "Nocturne",
    title: "Umbra Blades",
    description:
      "Passive: Every third attack, Nocturne slashes all adjacent enemies for 70% of his Attack Damage and bonus physical damage, and heals himself for 100% of the damage dealt. If only one target is hit, Nocturne increases his Attack Speed by 35% for 3 seconds."
  },
  {
    name: "Nunu",
    title: "Consume",
    description:
      "Willump bites his target, dealing magic damage. If Willump's target has less Health than he does before the bite, it deals an additional 50% damage and becomes true damage."
  },
  {
    name: "Olaf",
    title: "Berserker Rage",
    description:
      "Passive: Olaf gains Attack Speed for each 1% of missing health, and his attacks heal him."
  },
  {
    name: "Poppy",
    title: "Buckler Toss",
    description:
      "Poppy throws her buckler at the farthest enemy, dealing magic damage. The buckler then bounces back, granting Poppy a shield that blocks damage."
  },
  {
    name: "Pyke",
    title: "Phantom Undertow",
    description:
      "Pyke leaves a phantom at his location, then dashes behind the farthest enemy. After 1 second, his phantom returns to Pyke, dealing magic damage to all enemies it passes through and stunning them for a few seconds."
  },
  {
    name: "Rakan",
    title: "Battle Dance",
    description:
      "Rakan launches a feather toward his target, dealing magic damage to the first enemy hit. Rakan then heals all nearby allies for a percentage of their missing health, with an increased radius if the feather killed an enemy."
  },
  {
    name: "Rell",
    title: "Attract and Repel",
    description:
      "Rell leaps into the air, creating a tether between herself and her farthest ally. When she lands the tether is broken, granting all allies near and between them a shield for 4 seconds and stunning all enemies for seconds in the same area."
  },
  {
    name: "Riven",
    title: "Blade of the Dawn",
    description:
      "Riven empowers her blade, stunning nearby enemies for 1.5 seconds while dealing magic damage. For the next 8 seconds, she gains bonus Attack Damage."
  },
  {
    name: "Sejuani",
    title: "Fury of the North",
    description:
      "Sejuani signals Bristle to charge, dealing magic damage and stunning the target for 4 seconds. She then gains Frost Armor, granting her Armor and Magic Resist for a few seconds."
  },
  {
    name: "Senna",
    title: "Last Embrace",
    description:
      "Senna launches black mist toward the farthest enemy, stopping on the first enemy hit. That enemy is stunned for a few seconds, and all nearby enemies are dealt magic damage."
  },
  {
    name: "Sett",
    title: "Haymaker",
    description:
      "Sett pulls back for a punch, shredding flat armor for 10 seconds and dealing a percentage of his attack damage as physical damage to all enemies in the area."
  },
  {
    name: "Soraka",
    title: "Equinox",
    description:
      "Soraka calms the area around the enemy with the highest current percent mana, dealing magic damage to all enemies hit and increasing the cost of their next ability by 35%."
  },
  {
    name: "Syndra",
    title: "Force of Will",
    description:
      "Syndra grabs the nearest enemy and flings them towards the farthest enemy, dealing magic damage to all nearby enemies upon impact and stunning the thrown target for seconds."
  },
  {
    name: "Teemo",
    title: "Teemo's Cruelty",
    description:
      "Teemo scatters Infernal Souls around a random enemy. When an enemy nears an Infernal Soul (or after 3 seconds), it explodes dealing magic damage to nearby enemies and reducing their Attack Speed by 50%."
  },
  {
    name: "Thresh",
    title: "Death Sentence",
    description:
      "Thresh throws his scythe, chaining to the farthest enemy dealing magic damage and pulling them toward himself for a few seconds."
  },
  {
    name: "Tristana",
    title: "Rocket Jump",
    description:
      "Tristana leaps away from enemies, retargeting and gaining Attack Speed for 4 seconds. If there is an enemy adjacent to her, she instead leaps as far away from all enemies as she can."
  },
  {
    name: "Udyr",
    title: "Feral Instinct",
    description:
      "Udyr swaps between Turtle and Tiger stance with each cast, gaining the following benefits:Turtle: Gains a health shield for 4 seconds. Tiger: Strikes 3 times quickly with his next Basic Attack for a percentage of his Attack Damage."
  },
  {
    name: "Varus",
    title: "Hail of Arrows",
    description:
      "Varus fires a hail of arrows around his target, dealing a percentage of his Attack Damage as physical damage. Varus and allies within the area are blessed, causing them to deal bonus magic damage with their attacks for 6 seconds."
  },
  {
    name: "Vayne",
    title: "Silver Bolts",
    description:
      "Vayne's attacks apply Silver Bolts. The third stack consumes all stacks on the target to deal bonus true damage."
  },
  {
    name: "Vel'Koz",
    title: "Plasma Fission",
    description:
      "Vel'Koz channels a ray of energy toward the enemy nearest to the center of the battlefield over 3 seconds, dealing total magic damage over the duration. The beam widens as Vel'Koz channels, and he will turn if there are no enemies in the area."
  },
  {
    name: "Viego",
    title: "Soverign's Domination",
    description:
      "Viego corrupts his target's soul for 5 seconds, stunning them and dealing magic damage each second, increased by 50% each second. Viego will be interrupted if he is stunned. If his victim dies they are resurrected at full health to fight for him, but lose maximum health per second.Viego's allies prefer to not target Viego's victim while they're being corrupted, and corrupted enemies benefit from your team's Traits rather than their original owner's Traits."
  },
  {
    name: "Vladimir",
    title: "Transfusion",
    description: "Vladimir deals magic damage to the target and heals himself."
  },
  {
    name: "Volibear",
    title: "Doombringer",
    description:
      "Volibear leaps toward his target then slams the ground in a large area around him, removing any shields, dealing magic damage (double damage against shields) and knocking up and stunning enemies."
  },
  {
    name: "Yasuo",
    title: "Burning Blade",
    description:
      "Yasuo strikes his target, dealing magic damage. He then empowers his blade, gaining stacking bonus true damage on-hit for the rest of combat."
  },
  {
    name: "Ziggs",
    title: "Arcane Bomb",
    description:
      "Ziggs throws an arcane bomb at his target, dealing magic damage."
  },
  {
    name: "Zyra",
    title: "Grasping Roots",
    description:
      "Zyra sends a surge of vines toward the farthest enemy. Enemies hit by the vines are dealt magic damage and are stunned."
  }
];
